### ISSUE TITLE
Is the API down?

### ISSUE THREAD

**Issue by Badjas69** [Sylveon76/NHentaiAPI#1]
using your example:
```cs
var book = await client.GetBookAsync(ID);
```
I get nothing returned. any ideas on why this happened?

**Comment by andy840119** [comment]
https://twitter.com/fuckmaou/status/1084550608097603585
Maybe because n-Hentai remove its api temporarily.

**Comment by py7hon** [comment]
> using your example:
> 
> ```cs
> var book = await client.GetBookAsync(ID);
> ```
> 
> I get nothing returned. any ideas on why this happened?

Try use alternate API 
[Here](https://nhent.ai/api/)

**Comment by andy840119** [comment]
oops 
I'll try to make root url overridable

**Comment by andy840119** [comment]
@Badjas69 I made a update to make api work.(nuget is not update because n-hentai's api is not stable)
Please see the `README.md`.

**Comment by andy840119** [comment]
@py7hon 
https://github.com/nhentai-dev/nhent.ai
Is this project clone form official website 
or you rewrite it :thinking: ?

**Comment by py7hon** [comment]
> @py7hon
> https://github.com/nhentai-dev/nhent.ai
> Is this project clone form official website
> or you rewrite it 🤔 ?

not both, it's just a scrape with cheerio and reverse proxy for blocked countries

**Comment by andy840119** [comment]
@py7hon is https://nhent.ai/api/ down?

**Comment by py7hon** [comment]
yeah down after nhentai banned the ip

**Comment by py7hon** [comment]
@andy840119 Official nHentai API is up now 
[Tweet](https://twitter.com/fuckmaou/status/1113868849500303363)

**Comment by andy840119** [comment]
!!!!!!
I'll check it recently

**Comment by andy840119** [comment]
nHentai's API now seems stable,
If it down again pull another issue or tell me to re-open this issue.
