### ISSUE TITLE
Full API Docs?

### ISSUE THREAD

**Issue by ivanjx** [Sylveon76/NHentaiAPI#11]
Does NH publishes any documentations about their API? Or did you scrape this on your own? Thanks.

**Comment by andy840119** [comment]
I guess no 😢

**Comment by hentai-chan** [comment]
There are no official docs to the best of my knowledge, but I took some notes myself here: https://www.hentai-chan.dev/projects/hentai/api-endpoints

The example code is written in Python, but a somewhat experienced should have no problem translating this into any other language.
