### ISSUE TITLE
I believe NHentai updated their website, the API seems to be broken as a result...

### ISSUE THREAD

**Issue by Montegro** [Sylveon76/NHentaiAPI#12]
Went to go visit NHentai today to pull a few galleries for my software, noticed it now "Checks your browser" before loading in. Out of curiosity I attempted to have my program fetch one of the top results only for it to no longer load any information correctly.

Is there already an existing way around this? Or do we need to work on an update for the NHentaiAPI?

**Comment by andy840119** [comment]
Tested and seems like the API need some extra header.

https://nhentai.net/api/galleries/all?page=1
This URL works.

But it will return 503 error if not open in the browser.

I guess it's caused by n-hentai apply cloudflare to protect their website recently.

**Comment by SylveonDeko** [comment]
Solved, update to 1.5.0
