### ISSUE TITLE
API Wrapper Connection Issues Reporting Thread Thingy

### ISSUE THREAD

**Issue by Montegro** [Sylveon76/NHentaiAPI#16]
The new version of NHentaiAPI worked for last week, as far as I've been trying it out today the same issue as #12 is back.

**Comment by SylveonDeko** [comment]
I'll see what I can do, as I have no idea what's going on here or what nhentai is doing

**Comment by SylveonDeko** [comment]
There's also a possibility that the cloudflare check is in the way

**Comment by SylveonDeko** [comment]
Doesn't seem like I can really do anything, I dont know how others do it either

**Comment by andy840119** [comment]
Yes, i noticed that cloudflare has come back 😢 
Not really sure how to fix that(seems exrea header this time is not working).
.
Maybe find the mirror site(?) got help?

**Comment by SylveonDeko** [comment]
Mirror site doesn't have the api

**Comment by JCxYIS** [comment]
update: Seems like the cloudflare check has gone (again?)
I just tested and it works as usual :)

**Comment by SylveonDeko** [comment]
Hell knows, it'll probably be on and off again lol

**Comment by andy840119** [comment]
cloudflare in the n-hentai sometimes works, and sometimes not.
maybe cloudflare only works if got the large request or ddos?

**Comment by SylveonDeko** [comment]
Yes, from experience I know that you can setup anti ddos mode based on the
amount of traffic

**Comment by Montegro** [comment]
Would anyone happen to know if this api would help fix the situation a bit? https://github.com/RyuzakiH/CloudflareSolverRe

**Comment by SylveonDeko** [comment]
It may not work since they updated their captcha thing recently, but I'll
see if it works.

**Comment by SylveonDeko** [comment]
https://github.com/SylveonDeko/NHentaiAPI/releases/tag/1.6.0

**Comment by Montegro** [comment]
> https://github.com/SylveonDeko/NHentaiAPI/releases/tag/1.6.0

Any chance the ReadMe could be updated to give some instruction on how to use UserAgent? I'm a little lost.

**Comment by SylveonDeko** [comment]
Woops, will do that soon
