### ISSUE TITLE
Cookie Parsing Issues

### ISSUE THREAD

**Issue by cabeca1143** [Sylveon76/NHentaiAPI#17]
I'm not sure if this is the appropriate place, but I keep getting `403(Forbidden)` errors, and my suspicion is that I'm parsing my cookies wrong.
I already tried parsing to `Dictionary<string, string>` in a whole bunch of different ways, none of which worked.
I also couldn't find any documentation or info about this.

So may I ask for some clarification on what format exactly is expected for the `cookies` in the constructor of `NHentaiClient`?

**Comment by SylveonDeko** [comment]
key, value

but as of now it looks like they arent requiring it, but use this for the future
