### ISSUE TITLE
403 forbidden...

### ISSUE THREAD

**Issue by AlizerUncaged** [Sylveon76/NHentaiAPI#18]
seems like nhentai has been using cloudflare on attack mode, are there any ways around this?

![image](https://github.com/SylveonDeko/NHentaiAPI/assets/86959368/ca681fc7-d00f-4c88-8ecd-efd292696ddb)

**Comment by SylveonDeko** [comment]
1. use latest release
2. i explained how to get csrf in readme as of latest release (a few mins ago lel)
