### ISSUE TITLE
GetSearchPageListAsync(string keyword, int pageNum) ERROR

### ISSUE THREAD

**Issue by BloodLaad** [Sylveon76/NHentaiAPI#6]
Error converting value "g" to type 'NHentaiAPI.Models.Books.ImageType'. Path 'result[0].images.pages[21].t', line 1, position 939.

Requested value 'g' was not found.
----------------
Error if one of the images has the gif format
-> page 22 is a gif

**Comment by andy840119** [comment]
Can you provide any sample book id with gif page?
Thanks

**Comment by BloodLaad** [comment]
> 
> 
> Can you provide any sample book id with gif page?
> Thanks

E.g:
ID:288869 Page:22

**Comment by andy840119** [comment]
OK
I'll try to fix that recently 👍

**Comment by andy840119** [comment]
This issue has been fixed.
Check the latest [nuget package](https://www.nuget.org/packages/NHentaiAPI/1.3.0)

**Comment by BloodLaad** [comment]
ty
