### ISSUE TITLE
Can't get URL from ByteArray

### ISSUE THREAD

**Issue by ghost** [Sylveon76/NHentaiAPI#8]
I've tried every encoding/decoding method and I can't get the URL. Why do you return a byte array? Just return a string, I don't see any point other than to frustrate people. This goes for all methods that return a byte array. I can't do anything with it no matter who I ask or what solution I try

**Comment by andy840119** [comment]
Can you give me the sample code you use or error massage?
Or tun the test case then show me the resule?
.
It might caused by n-hentai change the api or your internet cannot access n-hentai.

**Comment by andy840119** [comment]
Do you means you want this method to make public?
https://github.com/andy840119/NHentaiAPI/blob/master/NHentaiAPI/NHentaiClient.cs#L95
.
Maybe you should ask or see the code first instead of blaming in here.

**Comment by ghost** [comment]
You're right, I'm sorry I was just frustrated. I'm not sure what to do with the ByteData though. Is it possible to get the URL?

**Comment by andy840119** [comment]
You can wait me for few days to update nuget, or fork this repo then modified it by yourself.

**Comment by andy840119** [comment]
@KotomiIchinose update nuget package and make a check new api you want.
